### ISSUE TITLE
support reading from csv file?

### ISSUE THREAD

**Issue by jingliu9** [z-plot/z-plot#5]
Then it might be more convenient to integrate with data processing libraries
which save result to csv. 
(https://github.com/jingliu9/z-plot/commit/74d1f0acbb993b6203073578b9fa5bc100a591f8)
quite simple

**Comment by tylerharter** [comment]
I think you can pass the path to a CSV file using the `table` param: https://github.com/z-plot/z-plot/blob/master/zplot/zplot.py#L2967
